title: 개발 블로그
email: ydong98@gmail.com
description: "개발에 대한 모든 것을 정리한 블로그입니다."
baseurl: ""
url: "https://ksideproject.github.io/"
twitter_username: 
github_username: kSideProject

# Build settings
theme: minima
plugins:
  - jekyll-feed